package com.settlement.pacing.api.error;

public enum ErrorCode {
    INVALID_REQUEST,
    AUTHENTICATION_FAILED,
    ACCESS_DENIED,
    RATE_LIMIT_EXCEEDED,
    CAMPAIGN_NOT_FOUND,
    CAMPAIGN_NOT_RESERVABLE,
    BUDGET_STATE_UNAVAILABLE,
    INSUFFICIENT_BUDGET,
    RESERVATION_CONFLICT,
    PACING_STATE_UPDATE_FAILED,
    STORAGE_UNAVAILABLE,
    INTERNAL_SERVER_ERROR
}
